In [1]:
# Recurssion_Assignment:-

In [3]:
# Q.1 Can you explain the logic and working of the Tower of Hanoi algorithm by writing a Java program?
"""How does the recursion work, and how are the movements of disks between rods accomplished?

A A

A

A

A

A

A

A

1

2

5

3

6

4

7

3 Disk

B B

B

B

B

B

B

B

C C

C

C

C

C

C

C
"""



''' The Tower of Hanoi is a classic problem in computer science and mathematics. The problem consists of three rods and a number of disks of different sizes, which can slide onto any rod. The puzzle starts with the disks in a neat stack in ascending order of size on one rod, the smallest at the top, thus making a conical shape.

The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules:

Only one disk can be moved at a time.
Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack or on an empty rod.
No disk may be placed on top of a smaller disk.
'''



# Here's a implementation of the Tower of Hanoi algorithm.


def tower_of_hanoi(n, source, target, auxiliary):
    if n == 1:
        print(f"Move disk 1 from rod {source} to rod {target}")
        return

    tower_of_hanoi(n - 1, source, auxiliary, target)
    print(f"Move disk {n} from rod {source} to rod {target}")
    tower_of_hanoi(n - 1, auxiliary, target, source)

if __name__ == "__main__":
    num_disks = 3
    source_rod = 'A'
    target_rod = 'C'
    auxiliary_rod = 'B'

    print("Tower of Hanoi Solution:")
    tower_of_hanoi(num_disks, source_rod, target_rod, auxiliary_rod)


Tower of Hanoi Solution:
Move disk 1 from rod A to rod C
Move disk 2 from rod A to rod B
Move disk 1 from rod C to rod B
Move disk 3 from rod A to rod C
Move disk 1 from rod B to rod A
Move disk 2 from rod B to rod C
Move disk 1 from rod A to rod C


Explanation:-

code defines a recursive function called tower_of_hanoi. The function takes four parameters:

n: the number of disks to move.
source: the rod from which to move the disks.
target: the rod to which to move the disks.
auxiliary: the auxiliary (or spare) rod to facilitate the movement.
Now, let's understand how the function works:

Base Case (n == 1):

If there is only one disk (n == 1), the function prints a statement indicating the movement of the disk from the source rod to the target rod.
This is the base case for the recursion.
Recursive Steps (n > 1):

If there are more than one disk (n > 1), the function does the following:
Recursively calls itself with n - 1 disks, moving them from the source rod to the auxiliary rod.
Prints a statement indicating the movement of the remaining disk (n) from the source rod to the target rod.
Recursively calls itself again with n - 1 disks, moving them from the auxiliary rod to the target rod.
The main block of the code sets up the initial parameters and calls the tower_of_hanoi function to solve the Tower of Hanoi problem:

his block initializes the number of disks (num_disks) and the labels for the source, target, and auxiliary rods. It then prints a message indicating that it's solving the Tower of Hanoi problem and calls the tower_of_hanoi function with the provided parameters. The recursive nature of the function takes care of the step-by-step movements of the disks, and the print statements show the solution.


In [4]:
# Q.2 Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.
'''Example 1:
Input: word1 = "horse", word2 = "ros"
Output: 3
Explanation:
horse -> rorse (replace 'h' with 'r')
rorse -> rose (remove 'r')
rose -> ros (remove 'e')
Example 2:
Input: word1 = "intention", word2 = "execution"
Output: 5
Explanation:
intention -> inention (remove 't')
inention -> enention (replace 'i' with 'e')
enention -> exention (replace 'n' with 'x')
exention -> exection (replace 'n' with 'c')
exection -> execution (insert 'u') '''


''' To solve this problem, we can use dynamic programming. we can create a 2D array where dp[i][j] represents the minimum number of operations required to convert the first i characters of word1 to the first j characters of word2. '''


# he recurrence relation is as follows:

''' dp[i][j] = min(
    dp[i-1][j-1] if word1[i-1] == word2[j-1] else dp[i-1][j-1] + 1,  # match or replace
    dp[i-1][j] + 1,  # delete
    dp[i][j-1] + 1   # insert
)
 '''


# code..!!

def minDistance(word1, word2):
    m, n = len(word1), len(word2)
    
    # Initialize the 2D array with zeros
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    
    # Initialize the first row and column
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j
    
    # Populate the DP array
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if word1[i - 1] == word2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = min(dp[i - 1][j - 1], dp[i - 1][j], dp[i][j - 1]) + 1
    
    # The result is in the bottom-right cell of the DP array
    return dp[m][n]

# Example 1
word1_1, word2_1 = "horse", "ros"
print(minDistance(word1_1, word2_1))  

# Example 2
word1_2, word2_2 = "intention", "execution"
print(minDistance(word1_2, word2_2))  


3
5


Explain:-

Function Definition:

The function minDistance takes two strings, word1 and word2, as input.
Initialization:

m and n are the lengths of word1 and word2 respectively.
dp is a 2D array initialized with zeros. It will be used to store the minimum number of operations for each subproblem.
Base Case Initialization:

The first row of dp represents the case when word1 is an empty string and we need to convert it to word2. The number of operations is equal to the length of word2.
The first column of dp represents the case when word2 is an empty string and we need to convert word1 to it. The number of operations is equal to the length of word1.
Populating the DP Array:

The nested loops iterate over each cell in the dp array.
If the characters at the current positions in word1 and word2 are the same, the value in the current cell is equal to the value in the diagonal cell (i.e., dp[i-1][j-1]).
If the characters are different, the value is calculated as the minimum of three neighboring cells plus 1, representing the operations of matching, deleting, or inserting a character.
Result:

The result is the value in the bottom-right cell of the dp array, representing the minimum number of operations to convert the entire word1 to word2.
Example Calls:

The examples at the end demonstrate the function with the provided test cases, printing the minimum number of operations for each conversion.






In [5]:
# Q. 3 Print the max value of the array [ 13, 1, -3, 22, 5].

# To find the maximum value in the array [13, 1, -3, 22, 5], we can use the built-in max() function in Python. 

arr = [13, 1, -3, 22, 5]
max_value = max(arr)

print("The maximum value in the array is:", max_value)


''' This code defines an array arr and then uses the max() function to find the maximum value in the array. '''

The maximum value in the array is: 22


In [6]:
# Q.4 Find the sum of the values of the array [92, 23, 15, -20, 10].

# To find the sum of the values in the array [92, 23, 15, -20, 10], we can use the built-in sum() function in Python.

arr = [92, 23, 15, -20, 10]
sum_of_values = sum(arr)

print("The sum of the values in the array is:", sum_of_values)


The sum of the values in the array is: 120


In [8]:
# Q.5 Given a number n. Print if it is an armstrong number or not.An armstrong number is a number if the sum of every digit in that number raised to the power of total digits in that number is equal to the number.
''' Example : 153 = 1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153 hence 153 is an armstrong number. (Easy)
Input1 : 153
Output1 : Yes
Input 2 : 134
Output2 : No '''


# program to determine if a given number is an Armstrong number:

def is_armstrong_number(n):
    # Convert the number to a string to find its length
    num_str = str(n)
    num_digits = len(num_str)

    # Calculate the sum of each digit raised to the power of the total digits
    armstrong_sum = sum(int(digit) ** num_digits for digit in num_str)

    # Check if the sum is equal to the original number
    return armstrong_sum == n

# Test cases
input1 = 153
output1 = is_armstrong_number(input1)
print(f"Input 1: {input1}, Output 1: {'Yes' if output1 else 'No'}")

input2 = 134
output2 = is_armstrong_number(input2)
print(f"Input 2: {input2}, Output 2: {'Yes' if output2 else 'No'}")



''' This program defines a function is_armstrong_number that takes an integer n as input and returns True if it is an Armstrong number, and False otherwise.'''



Input 1: 153, Output 1: Yes
Input 2: 134, Output 2: No


' This program defines a function is_armstrong_number that takes an integer n as input and returns True if it is an Armstrong number, and False otherwise.'

Explaination:-

Function Definition:

The function is_armstrong_number takes an integer n as input.
Convert to String:

num_str = str(n): Convert the number to a string to find its length.
Calculate the Number of Digits:

num_digits = len(num_str): Find the number of digits in the given number.
Calculate Armstrong Sum:

armstrong_sum = sum(int(digit) ** num_digits for digit in num_str): Calculate the sum of each digit raised to the power of the total digits. This is done using a generator expression.
Check for Armstrong Number:

return armstrong_sum == n: Check if the calculated sum is equal to the original number. If it is, then the number is an Armstrong number.
Test Cases:

Two test cases are provided at the end to demonstrate the function:
input1 = 153: The function is called with this input, and the result is printed.
input2 = 134: Similarly, the function is called with this input, and the result is printed.
Output:

The output is printed in the format: Input: {input}, Output: {'Yes' if output else 'No'}. It indicates whether the given number is an Armstrong number or not.





